// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lS_r9ltZCIE7_2GssMQjclEAbrvk4Pg',
    appId: '1:348519866298:web:4988fd04a781bf820e0783',
    messagingSenderId: '348519866298',
    projectId: 'music-app-db-hoa935',
    authDomain: 'music-app-db-hoa935.firebaseapp.com',
    storageBucket: 'music-app-db-hoa935.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdP02WebwIIfgPDakyVrFQ4XqJnBDpLI',
    appId: '1:348519866298:android:2587523da349b88a0e0783',
    messagingSenderId: '348519866298',
    projectId: 'music-app-db-hoa935',
    storageBucket: 'music-app-db-hoa935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVly0T3XSQeja_itleVDCjYhxrzqpZSsA',
    appId: '1:348519866298:ios:f7887fdf53ea695c0e0783',
    messagingSenderId: '348519866298',
    projectId: 'music-app-db-hoa935',
    storageBucket: 'music-app-db-hoa935.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVly0T3XSQeja_itleVDCjYhxrzqpZSsA',
    appId: '1:348519866298:ios:f7887fdf53ea695c0e0783',
    messagingSenderId: '348519866298',
    projectId: 'music-app-db-hoa935',
    storageBucket: 'music-app-db-hoa935.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4lS_r9ltZCIE7_2GssMQjclEAbrvk4Pg',
    appId: '1:348519866298:web:704c10b59b271db20e0783',
    messagingSenderId: '348519866298',
    projectId: 'music-app-db-hoa935',
    authDomain: 'music-app-db-hoa935.firebaseapp.com',
    storageBucket: 'music-app-db-hoa935.firebasestorage.app',
  );

}